### ISSUE TITLE
turtle don't go through ore veins

### ISSUE THREAD

**Issue by DOlivier4444** [Equbuxu/mine#11]
The branch function of the turtle work as planned, but the turtle don't go through ore veins.

I'm using cc-tweaked-1.16.5-1.101.3 (CraftOS1.18) on a 1.16.5 modded game

![Capture d'écran 2023-09-30 153016](https://github.com/Equbuxu/mine/assets/146378066/c7edda12-1aa5-45e1-b946-61548625423e)

**Comment by Equbuxu** [comment]
Hi, `oreTraversalRadius` might be set to 0 in the config (it is if you haven't changed it manually), check line 14 in mine.lua and increase it to something like 5.

**Comment by DOlivier4444** [comment]
That was it, thanks a lot !
Your code is amazing !
